import { User, Listing, Media, Unlock, Payout, Review, SupportTicket } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user-admin-isa',
    name: 'Isa Mohamed',
    email: 'IsaMohamed92@gmail.com',
    phone: '+254 741 367 051',
    role: 'admin',
    verification_status: 'top_rated',
    trust_score: 100,
    trust_tier: 'Platinum',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    national_id_number: '28491023',
    national_id_masked: '2849****',
    id_front_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    id_back_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    face_selfie_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    face_liveness_score: 99.8,
    kyc_submitted_at: '2025-01-10 09:00 EAT',
    kyc_verified_at: '2025-01-10 09:05 EAT',
    member_since: 'Founder & Super Admin',
    total_listings: 1,
  },
  {
    id: 'user-poster-1',
    name: 'Wanjiku Mwangi',
    email: 'wanjiku.mwangi@kiota.co.ke',
    phone: '+254 722 345 678',
    role: 'poster',
    track: 'community',
    verification_status: 'top_rated',
    trust_score: 98,
    trust_tier: 'Silver',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    national_id_number: '29381744',
    national_id_masked: '2938****',
    id_front_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    id_back_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    face_selfie_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
    face_liveness_score: 99.2,
    kyc_submitted_at: '2025-03-12 14:20 EAT',
    kyc_verified_at: '2025-03-12 14:35 EAT',
    member_since: 'March 2025',
    total_listings: 4,
  },
  {
    id: 'user-seeker-1',
    name: 'Brian Kipchoge',
    email: 'brian.kip@gmail.com',
    phone: '+254 711 987 654',
    role: 'seeker',
    verification_status: 'verified',
    trust_score: 95,
    trust_tier: 'Platinum',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    national_id_number: '33129845',
    national_id_masked: '3312****',
    member_since: 'January 2026',
    total_listings: 0,
  },
  {
    id: 'user-poster-pending-1',
    name: 'Kelvin Mutua',
    email: 'kelvin.mutua@gmail.com',
    phone: '+254 712 554 990',
    role: 'poster',
    verification_status: 'pending_verification',
    trust_score: 75,
    trust_tier: 'Bronze',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    national_id_number: '35892104',
    national_id_masked: '3589****',
    id_front_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    id_back_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    face_selfie_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80',
    face_liveness_score: 98.4,
    kyc_submitted_at: '2026-09-02 11:15 EAT',
    member_since: 'September 2026',
    total_listings: 1,
  },
  {
    id: 'user-poster-2',
    name: 'Hassan Omar (Caretaker)',
    email: 'hassan.o@gmail.com',
    phone: '+254 733 112 233',
    role: 'poster',
    track: 'community',
    verification_status: 'verified',
    trust_score: 92,
    trust_tier: 'Gold',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    national_id_number: '31092451',
    national_id_masked: '3109****',
    id_front_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    id_back_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    face_selfie_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80',
    face_liveness_score: 97.9,
    kyc_submitted_at: '2025-11-04 10:10 EAT',
    kyc_verified_at: '2025-11-04 10:25 EAT',
    member_since: 'November 2024',
    total_listings: 8, // 8 genuine listings -> Reaches Community Gold at 50%!
  },
  {
    id: 'user-poster-3',
    name: 'Faith Njeri',
    email: 'faith.njeri@gmail.com',
    phone: '+254 701 445 566',
    role: 'poster',
    track: 'community',
    verification_status: 'top_rated',
    trust_score: 100,
    trust_tier: 'Bronze',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    national_id_number: '28441990',
    national_id_masked: '2844****',
    id_front_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    id_back_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    face_selfie_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
    face_liveness_score: 99.5,
    kyc_submitted_at: '2025-08-19 16:30 EAT',
    kyc_verified_at: '2025-08-19 16:45 EAT',
    member_since: 'August 2025',
    total_listings: 1, // Community Bronze (20%)
  },
  {
    id: 'user-partner-apex',
    name: 'Apex Property Management Ltd',
    email: 'listings@apexmanagement.co.ke',
    phone: '+254 720 998 811',
    role: 'poster',
    track: 'partner',
    agency_name: 'Apex Property Caretakers & Agency Ltd',
    business_reg_number: 'PVT-Q928410',
    agency_verified: true,
    verification_status: 'agent',
    trust_score: 98,
    trust_tier: 'Platinum',
    avatar_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    member_since: 'Agency Partner since 2024',
    total_listings: 42, // Partner Platinum (40+ listings -> 75% + premium pricing)
  },
  {
    id: 'user-partner-landmark',
    name: 'Landmark Caretakers Group',
    email: 'info@landmarkcaretakers.co.ke',
    phone: '+254 733 887 766',
    role: 'poster',
    track: 'partner',
    agency_name: 'Landmark Caretakers & Realty Group',
    business_reg_number: 'BN-883912',
    agency_verified: true,
    verification_status: 'agent',
    trust_score: 91,
    trust_tier: 'Silver',
    avatar_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
    member_since: 'Agency Partner since 2025',
    total_listings: 18, // Partner Silver (15-29 listings -> 40%)
  },
];

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    category: 'Rentals',
    property_type: '1 Bedroom Apartment',
    title: 'Spacious 1BR with Balcony & Borehole',
    price: 32000,
    price_period: 'month',
    deposit: 32000,
    area: 'Kilimani, Nairobi',
    gps_lat: -1.2891,
    gps_lng: 36.7821,
    exact_landmark: 'Wood Avenue Plaza, 3rd Floor Apt 3C, next to Yaya Centre bypass',
    description: 'Freshly repainted spacious 1-bedroom apartment with high ceilings, separate laundry area, dedicated parking, reliable borehole water supply, 24/7 CCTV, and high-speed fiber internet connection ready.',
    status: 'active',
    poster_id: 'user-poster-1',
    unlock_price: 250,
    bedrooms: 1,
    bathrooms: 1,
    floor_size: '65 sq.m',
    features: ['Borehole Water', '24/7 Security Guard', 'Prepaid Token Meter', 'Dedicated Parking', 'High Speed Fibre', 'Balcony'],
    created_at: '2026-08-28T10:00:00Z',
    view_count: 342,
  },
  {
    id: 'listing-2',
    category: 'Rentals',
    property_type: 'Modern Studio / Bedsitter',
    title: 'Modern Executive Bedsitter with Tiled Balcony',
    price: 13500,
    price_period: 'month',
    deposit: 13500,
    area: 'Roysambu (TRM Drive), Nairobi',
    gps_lat: -1.2185,
    gps_lng: 36.8876,
    exact_landmark: 'Golden Heights Court, 2nd Floor Unit 204, along Lumumba Drive, behind TRM',
    description: 'Clean, secure, and modern executive bedsitter with ceramic tiles, instant hot water shower, separate modern kitchen sink, token electricity, and biometric main gate access.',
    status: 'active',
    poster_id: 'user-poster-2',
    unlock_price: 200,
    bedrooms: 1,
    bathrooms: 1,
    floor_size: '35 sq.m',
    features: ['Instant Shower', 'Biometric Gate', 'Prepaid Token Meter', 'CCTV on all floors', 'Rooftop Hanging Line', 'Zuku & Safaricom Wi-Fi ready'],
    created_at: '2026-08-29T14:30:00Z',
    view_count: 512,
  },
  {
    id: 'listing-3',
    category: 'Shops & Offices',
    property_type: 'Prime Retail Shop',
    title: 'Ground Floor Retail Stall with High Footfall',
    price: 48000,
    price_period: 'month',
    deposit: 96000,
    area: 'CBD (Moi Avenue), Nairobi',
    gps_lat: -1.2833,
    gps_lng: 36.8239,
    exact_landmark: 'Kenwood Exhibition Arcade, Stall G-14, directly opposite Khoja Roundabout',
    description: 'High visibility ground floor glass-fronted commercial stall. Ideal for electronics, boutique, beauty parlour, or agency. Comes with heavy duty roller shutter, sub-metered power, and shared clean washrooms.',
    status: 'active',
    poster_id: 'user-poster-1',
    unlock_price: 350,
    floor_size: '22 sq.m',
    features: ['High Footfall Zone', 'Glass Frontage', 'Roller Shutter', 'Sub-metered Electricity', 'Loading Bay Access', '24/7 Security'],
    created_at: '2026-08-30T09:15:00Z',
    view_count: 280,
  },
  {
    id: 'listing-4',
    category: 'Airbnb',
    property_type: 'Luxury Furnished Studio',
    title: 'Sunset Views Studio with Heated Pool & Gym',
    price: 4500,
    price_period: 'night',
    deposit: 0,
    area: 'Westlands, Nairobi',
    gps_lat: -1.2683,
    gps_lng: 36.8045,
    exact_landmark: 'Skyline Skyrise Suites, 11th Floor Suite 1102, Rhapta Road Westlands',
    description: 'Stylishly curated Airbnb with super-fast 100Mbps Wi-Fi, 55-inch 4K Smart TV with Netflix, king bed with orthopaedic mattress, fully equipped kitchenette, infinity heated rooftop pool, and gym access.',
    status: 'active',
    poster_id: 'user-poster-3',
    unlock_price: 300,
    bedrooms: 1,
    bathrooms: 1,
    floor_size: '48 sq.m',
    features: ['Self Check-in Keypad', 'Rooftop Heated Pool', 'Equipped Gym', 'High Speed 100Mbps Wi-Fi', 'Netflix & DSTV', 'Backup Generator'],
    created_at: '2026-08-31T16:00:00Z',
    view_count: 678,
  },
  {
    id: 'listing-5',
    category: 'Rentals',
    property_type: '2 Bedroom Master Ensuite',
    title: 'Gated Estate 2BR Master Ensuite with Garden',
    price: 42000,
    price_period: 'month',
    deposit: 42000,
    area: 'South B (Hazina), Nairobi',
    gps_lat: -1.3122,
    gps_lng: 36.8378,
    exact_landmark: 'Hazina Estate Phase 3, Court 4, House No. 88B, near Plainsview Hospital',
    description: 'Serene 2-bedroom home in a family-friendly gated estate. Large master bedroom with fitted wardrobes, pantry, laundry drying yard, private balcony, and ample children playing ground.',
    status: 'active',
    poster_id: 'user-poster-2',
    unlock_price: 250,
    bedrooms: 2,
    bathrooms: 2,
    floor_size: '90 sq.m',
    features: ['Master Ensuite', 'Gated Community', 'Playground', 'Borehole + City Water', 'Individual Water Tank (1000L)', '2 Car Parking Slots'],
    created_at: '2026-09-01T08:00:00Z',
    view_count: 195,
  },
  {
    id: 'listing-6',
    category: 'Airbnb',
    property_type: '2BR Beachside Villa',
    title: 'Ocean Breeze 2BR with Private Garden & Pool',
    price: 7500,
    price_period: 'night',
    deposit: 0,
    area: 'Nyali, Mombasa',
    gps_lat: -4.0321,
    gps_lng: 39.7118,
    exact_landmark: 'Palm Breeze Villas, Unit 5, Beach Road Nyali, 300m from Nyali Beach',
    description: 'Charming coastal retreat with Swahili architecture, air conditioning in all rooms, private swimming pool, chef on call upon request, and 3 minutes walk to the sandy Nyali beach.',
    status: 'active',
    poster_id: 'user-poster-3',
    unlock_price: 350,
    bedrooms: 2,
    bathrooms: 2,
    floor_size: '120 sq.m',
    features: ['Air Conditioning', 'Private Pool', '300m to Beach', 'Swahili Daybed', 'Solar Hot Water', 'Daily Housekeeping'],
    created_at: '2026-09-01T12:00:00Z',
    view_count: 420,
  },
  {
    id: 'listing-7-pending',
    category: 'Rentals',
    property_type: '2 Bedroom Apartment',
    title: 'Sunny 2BR with Balcony & City Water',
    price: 28000,
    price_period: 'month',
    deposit: 28000,
    area: 'Ruaka, Kiambu',
    gps_lat: -1.2056,
    gps_lng: 36.7789,
    exact_landmark: 'Silver Oak Apartments, Block B, 4th Floor Door 402, Quickmart Ruaka Road',
    description: 'Newly finished 2-bedroom unit with spacious kitchen, fitted closets, large balcony with valley views, secure biometric entrance, and reliable Wi-Fi connections.',
    status: 'pending_review',
    poster_id: 'user-poster-1',
    unlock_price: 200,
    bedrooms: 2,
    bathrooms: 1,
    floor_size: '75 sq.m',
    features: ['Borehole Water', 'Balcony', '24/7 Security Guard', 'Prepaid Token Meter', 'Dedicated Parking Slot'],
    created_at: '2026-09-02T06:20:00Z',
    view_count: 12,
  },
  {
    id: 'listing-8-pending',
    category: 'Shops & Offices',
    property_type: 'Exhibition Stall / Booth',
    title: 'Busy Tech Arcade Stall with Glass Shelves',
    price: 35000,
    price_period: 'month',
    deposit: 70000,
    area: 'CBD (Moi Avenue), Nairobi',
    gps_lat: -1.2833,
    gps_lng: 36.8239,
    exact_landmark: 'Jamia Plaza Arcade, 1st Floor Stall F-09, Tubman Road Entrance',
    description: 'High traffic electronics & phone repair stall. Fully fitted LED displays, reinforced glass sliding doors, sub-metered power, and fast security response.',
    status: 'pending_review',
    poster_id: 'user-poster-2',
    unlock_price: 300,
    floor_size: '18 sq.m',
    features: ['High Footfall Zone', 'Glass Frontage', 'Roller Shutter', 'Sub-metered Electricity'],
    created_at: '2026-09-02T07:15:00Z',
    view_count: 8,
  },
  {
    id: 'listing-9-flagged',
    category: 'Rentals',
    property_type: 'Modern Studio / Bedsitter',
    title: 'Cheap Bedsitter in Kileleshwa',
    price: 8000,
    price_period: 'month',
    deposit: 8000,
    area: 'Kileleshwa, Nairobi',
    gps_lat: -1.2816,
    gps_lng: 36.7884,
    exact_landmark: 'Mandera Road, unverified building',
    description: 'Bedsitter with water and tokens.',
    status: 'rejected',
    rejection_reason: 'Price unrealistic for Kileleshwa; GPS timestamp does not match live on-site coordinates.',
    poster_id: 'user-poster-2',
    unlock_price: 250,
    bedrooms: 1,
    bathrooms: 1,
    features: ['Prepaid Token Meter'],
    created_at: '2026-09-01T18:00:00Z',
    view_count: 5,
  },
  {
    id: 'listing-10',
    category: 'Shops & Offices',
    property_type: 'Executive Office Suite',
    title: 'Executive Grade-A Office Suite with High Speed Fibre',
    price: 65000,
    price_period: 'month',
    deposit: 65000,
    area: 'Upper Hill, Nairobi',
    gps_lat: -1.2991,
    gps_lng: 36.8155,
    exact_landmark: 'Britam Tower Annex, 8th Floor Suite 802, Hospital Road Upper Hill',
    description: 'Managed by Apex Property Caretakers & Agency Ltd. Grade-A partitioned executive office suite with dedicated conference room, reception area, biometric entry, backup generator, high-speed fibre internet, and 2 reserved basement parking slots.',
    status: 'active',
    poster_id: 'user-partner-apex',
    unlock_price: 300,
    floor_size: '95 sq.m',
    features: ['Biometric Access', 'High Speed Fibre', 'Backup Generator', 'Dedicated Parking', '24/7 CCTV', 'Elevator Access'],
    created_at: '2026-09-02T10:00:00Z',
    view_count: 318,
  },
];

export const SEED_MEDIA: Media[] = [
  // Listing 1
  {
    id: 'media-1-1',
    listing_id: 'listing-1',
    url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-28 09:45 EAT',
    capture_location: 'GPS -1.2891, 36.7821 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Living room with natural light and wooden floors',
  },
  {
    id: 'media-1-2',
    listing_id: 'listing-1',
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-28 09:47 EAT',
    capture_location: 'GPS -1.2891, 36.7821 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Bedroom with built-in wardrobes',
  },
  {
    id: 'media-1-3',
    listing_id: 'listing-1',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-28 09:49 EAT',
    capture_location: 'GPS -1.2891, 36.7821 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Modern kitchen with granite countertops',
  },
  {
    id: 'media-1-4',
    listing_id: 'listing-1',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-interior-design-41006-large.mp4',
    type: 'video',
    capture_timestamp: '2026-08-28 09:52 EAT',
    capture_location: 'GPS -1.2891, 36.7821 ± 2m Live Verified Walkthrough',
    is_live_capture: true,
    caption: 'Live video walkthrough of 1BR unit and balcony',
  },
  // Listing 2
  {
    id: 'media-2-1',
    listing_id: 'listing-2',
    url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-29 14:15 EAT',
    capture_location: 'GPS -1.2185, 36.8876 ± 4m Live Verified',
    is_live_capture: true,
    caption: 'Clean studio room with tiled finish',
  },
  {
    id: 'media-2-2',
    listing_id: 'listing-2',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-29 14:18 EAT',
    capture_location: 'GPS -1.2185, 36.8876 ± 4m Live Verified',
    is_live_capture: true,
    caption: 'Instant shower and clean washroom',
  },
  // Listing 3
  {
    id: 'media-3-1',
    listing_id: 'listing-3',
    url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-30 09:00 EAT',
    capture_location: 'GPS -1.2833, 36.8239 ± 2m Live Verified',
    is_live_capture: true,
    caption: 'Front glass stall view from corridor',
  },
  {
    id: 'media-3-2',
    listing_id: 'listing-3',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-30 09:03 EAT',
    capture_location: 'GPS -1.2833, 36.8239 ± 2m Live Verified',
    is_live_capture: true,
    caption: 'Interior shelves and power points',
  },
  // Listing 4
  {
    id: 'media-4-1',
    listing_id: 'listing-4',
    url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-31 15:40 EAT',
    capture_location: 'GPS -1.2683, 36.8045 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Designer studio bedroom area',
  },
  {
    id: 'media-4-2',
    listing_id: 'listing-4',
    url: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-08-31 15:45 EAT',
    capture_location: 'GPS -1.2683, 36.8045 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Rooftop pool and sunset terrace',
  },
  {
    id: 'media-4-3',
    listing_id: 'listing-4',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-modern-luxury-apartment-living-room-41008-large.mp4',
    type: 'video',
    capture_timestamp: '2026-08-31 15:50 EAT',
    capture_location: 'GPS -1.2683, 36.8045 ± 2m Live Verified Walkthrough',
    is_live_capture: true,
    caption: 'Live host walkthrough and pool view',
  },
  // Listing 5
  {
    id: 'media-5-1',
    listing_id: 'listing-5',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-01 07:35 EAT',
    capture_location: 'GPS -1.3122, 36.8378 ± 4m Live Verified',
    is_live_capture: true,
    caption: 'Front facade and compound parking',
  },
  // Listing 6
  {
    id: 'media-6-1',
    listing_id: 'listing-6',
    url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-01 11:30 EAT',
    capture_location: 'GPS -4.0321, 39.7118 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Villa pool and Swahili lounge patio',
  },
  // Listing 7 (Pending Review)
  {
    id: 'media-7-1',
    listing_id: 'listing-7-pending',
    url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-02 06:10 EAT',
    capture_location: 'GPS -1.2056, 36.7789 ± 2m Live Verified',
    is_live_capture: true,
    caption: 'Living room overlooking Ruaka valley',
  },
  {
    id: 'media-7-2',
    listing_id: 'listing-7-pending',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-02 06:14 EAT',
    capture_location: 'GPS -1.2056, 36.7789 ± 2m Live Verified',
    is_live_capture: true,
    caption: 'Kitchen fittings and balcony access',
  },
  // Listing 8 (Pending Review)
  {
    id: 'media-8-1',
    listing_id: 'listing-8-pending',
    url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-02 07:05 EAT',
    capture_location: 'GPS -1.2833, 36.8239 ± 3m Live Verified',
    is_live_capture: true,
    caption: 'Front stall glass shelves with roller shutter',
  },
  // Listing 9 (Rejected)
  {
    id: 'media-9-1',
    listing_id: 'listing-9-flagged',
    url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
    type: 'photo',
    capture_timestamp: '2026-09-01 17:45 EAT',
    capture_location: 'GPS -1.2816, 36.7884 ± 15m (Suspect GPS)',
    is_live_capture: false,
    caption: 'Photo uploaded from gallery (not in-app camera)',
  },
];

export const SEED_UNLOCKS: Unlock[] = [
  {
    id: 'unlock-101',
    listing_id: 'listing-1',
    seeker_id: 'user-seeker-1',
    amount_paid: 250,
    payment_reference: 'MPESA-QKD78X904',
    timestamp: '2026-09-01T15:30:00Z',
    seeker_phone: '+254 711 987 654',
  },
  {
    id: 'unlock-102',
    listing_id: 'listing-4',
    seeker_id: 'user-seeker-1',
    amount_paid: 300,
    payment_reference: 'MPESA-QLM99Z412',
    timestamp: '2026-09-02T08:15:00Z',
    seeker_phone: '+254 711 987 654',
  },
  {
    id: 'unlock-103',
    listing_id: 'listing-1',
    seeker_id: 'user-poster-2',
    amount_paid: 250,
    payment_reference: 'MPESA-QKN44Y881',
    timestamp: '2026-08-30T11:20:00Z',
    seeker_phone: '+254 733 112 233',
  },
  {
    id: 'unlock-104',
    listing_id: 'listing-3',
    seeker_id: 'user-seeker-1',
    amount_paid: 350,
    payment_reference: 'MPESA-QKB12P553',
    timestamp: '2026-08-31T09:40:00Z',
    seeker_phone: '+254 711 987 654',
  },
  {
    id: 'unlock-105',
    listing_id: 'listing-10',
    seeker_id: 'user-seeker-1',
    amount_paid: 300,
    payment_reference: 'MPESA-QKX55M891',
    timestamp: '2026-09-02T16:30:00Z',
    seeker_phone: '+254 711 987 654',
  },
];

export const SEED_PAYOUTS: Payout[] = [
  {
    id: 'payout-201',
    poster_id: 'user-poster-1',
    unlock_id: 'unlock-101',
    amount: 125, // 50% of 250 (Platinum Tier)
    status: 'pending',
    tier_at_time: 'Platinum',
    earn_percentage: 50,
    release_time: '2026-09-03 15:30 EAT',
    mpesa_phone: '+254 722 345 678',
    listing_title: 'Spacious 1BR with Balcony & Borehole',
  },
  {
    id: 'payout-202',
    poster_id: 'user-poster-1',
    unlock_id: 'unlock-103',
    amount: 125,
    status: 'released',
    tier_at_time: 'Platinum',
    earn_percentage: 50,
    release_time: '2026-08-31 11:20 EAT',
    released_at: '2026-08-31 11:22 EAT',
    approved_by: 'Isa Mohamed (Admin)',
    mpesa_phone: '+254 722 345 678',
    mpesa_receipt: 'QKT892LL4M',
    listing_title: 'Spacious 1BR with Balcony & Borehole',
  },
  {
    id: 'payout-203',
    poster_id: 'user-poster-1',
    unlock_id: 'unlock-104',
    amount: 105, // 30% of 350 (Community Silver)
    status: 'released',
    tier_at_time: 'Silver',
    track_at_time: 'community',
    earn_percentage: 30,
    release_time: '2026-09-01 09:40 EAT',
    released_at: '2026-09-01 09:45 EAT',
    approved_by: 'Isa Mohamed (Admin)',
    mpesa_phone: '+254 722 345 678',
    mpesa_receipt: 'QKV119PP7K',
    listing_title: 'Ground Floor Retail Stall with High Footfall',
  },
  {
    id: 'payout-204',
    poster_id: 'user-poster-2',
    unlock_id: 'unlock-102',
    amount: 150, // 50% of 300 (Community Gold Tier for Caretaker Hassan Omar)
    status: 'pending',
    tier_at_time: 'Gold',
    track_at_time: 'community',
    earn_percentage: 50,
    release_time: '2026-09-04 08:15 EAT',
    mpesa_phone: '+254 733 112 233',
    listing_title: 'Sunset Views Studio with Heated Pool & Gym',
  },
  {
    id: 'payout-205',
    poster_id: 'user-poster-2',
    unlock_id: 'unlock-101',
    amount: 125, // 50% of 250 (Community Gold Tier)
    status: 'flagged',
    tier_at_time: 'Gold',
    track_at_time: 'community',
    earn_percentage: 50,
    flag_reason: 'Seeker reported locked gate key code required verification.',
    release_time: 'On Escrow Safeguard Hold',
    mpesa_phone: '+254 733 112 233',
    listing_title: 'Modern Executive Bedsitter with Tiled Balcony',
  },
  {
    id: 'payout-206',
    poster_id: 'user-partner-apex',
    unlock_id: 'unlock-105',
    amount: 180, // Stepped down to 60% of 300 (base was Platinum 75%)
    status: 'released',
    tier_at_time: 'Platinum',
    track_at_time: 'partner',
    base_earn_percentage: 75,
    earn_percentage: 60,
    is_stepped_down: true,
    monthly_unlock_count: 22,
    step_down_note: 'Monthly volume cap applied: Unlock #22 in September exceeded the 20-unlock cap (stepped down from Platinum 75% to Gold 60% rate).',
    release_time: '2026-09-02 16:30 EAT',
    released_at: '2026-09-02 16:35 EAT',
    approved_by: 'Automated Safeguard & Isa Mohamed',
    mpesa_phone: '+254 720 998 811',
    mpesa_receipt: 'QKAPEX7790',
    listing_title: 'Executive Grade-A Office Suite with High Speed Fibre',
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'review-1',
    listing_id: 'listing-1',
    seeker_id: 'user-seeker-1',
    seeker_name: 'Brian K.',
    accurate: true,
    rating: 5,
    comment: 'Went on site today at Wood Avenue. Exactly as captured in the camera video. Landlord Wanjiku was very professional, water is flowing 24/7.',
    created_at: '2026-09-01T17:00:00Z',
  },
  {
    id: 'review-2',
    listing_id: 'listing-1',
    seeker_id: 'user-poster-2',
    seeker_name: 'Hassan O.',
    accurate: true,
    rating: 5,
    comment: 'Verified location and unit size matches 100%. No hidden agency extortion fees.',
    created_at: '2026-08-30T14:10:00Z',
  },
  {
    id: 'review-3',
    listing_id: 'listing-4',
    seeker_id: 'user-seeker-1',
    seeker_name: 'Brian K.',
    accurate: true,
    rating: 5,
    comment: 'The rooftop sunset view is real! Keypad access was smooth. Recommended host.',
    created_at: '2026-09-02T10:30:00Z',
  },
];

export const SEED_TICKETS: SupportTicket[] = [
  {
    id: 'ticket-101',
    userId: 'user-poster-1',
    userName: 'Wanjiku Mwangi',
    userPhone: '+254 722 345 678',
    userRole: 'poster',
    category: 'listing_approval',
    subject: 'Verification status for Kilimani 2BR Apartment',
    status: 'resolved',
    createdAt: '2026-09-02T09:15:00Z',
    lastActivityAt: '2026-09-02T10:00:00Z',
    listingId: 'listing-1',
    listingTitle: 'Modern 2BR Master Ensuite - Wood Avenue',
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-poster-1',
        senderName: 'Wanjiku Mwangi',
        senderRole: 'poster',
        text: 'Habari Kiota Support! I submitted my in-app video capture for the Wood Avenue listing. When will it be fully live for seekers?',
        timestamp: '2026-09-02T09:15:00Z',
      },
      {
        id: 'msg-2',
        senderId: 'user-admin-isa',
        senderName: 'Isa Mohamed (Kiota Concierge)',
        senderRole: 'support',
        isAdminResponse: true,
        text: 'Jambo Wanjiku! Your National ID and on-site camera watermark matched GPS coordinates with zero discrepancies. Your listing has been approved and is now active on the public feed! Seekers are already discovering it.',
        timestamp: '2026-09-02T10:00:00Z',
      },
    ],
  },
  {
    id: 'ticket-102',
    userId: 'user-seeker-1',
    userName: 'Brian Kipchoge',
    userPhone: '+254 711 987 654',
    userRole: 'seeker',
    category: 'general',
    subject: 'Accessing unlocked property directions & landlord contact',
    status: 'resolved',
    createdAt: '2026-09-02T14:20:00Z',
    lastActivityAt: '2026-09-02T14:45:00Z',
    listingId: 'listing-1',
    listingTitle: 'Modern 2BR Master Ensuite - Wood Avenue',
    unlockId: 'unlock-1',
    messages: [
      {
        id: 'msg-3',
        senderId: 'user-seeker-1',
        senderName: 'Brian Kipchoge',
        senderRole: 'seeker',
        text: 'Hi Kiota team, I paid the KES 300 unlock fee via M-Pesa. How long do I have to dispute if the house is occupied or landlord is unreachable?',
        timestamp: '2026-09-02T14:20:00Z',
      },
      {
        id: 'msg-4',
        senderId: 'user-admin-isa',
        senderName: 'Kiota Escrow Desk (Nairobi)',
        senderRole: 'support',
        isAdminResponse: true,
        text: 'Hello Brian! You are covered by our 24-Hour 100% Seeker Money-Back Escrow Guarantee. If you visit on-site and find the unit taken or misstated, flag it in your dashboard within 24 hours and your KES 300 will be refunded to your original M-Pesa line.',
        timestamp: '2026-09-02T14:45:00Z',
      },
    ],
  },
  {
    id: 'ticket-103',
    userId: 'user-poster-1',
    userName: 'Wanjiku Mwangi',
    userPhone: '+254 722 345 678',
    userRole: 'poster',
    category: 'payout_delay',
    subject: 'Partner Track Upgrade & Payout Share Tier',
    status: 'open',
    createdAt: '2026-09-03T07:10:00Z',
    lastActivityAt: '2026-09-03T07:10:00Z',
    messages: [
      {
        id: 'msg-5',
        senderId: 'user-poster-1',
        senderName: 'Wanjiku Mwangi',
        senderRole: 'poster',
        text: 'Hello Admin! I have 4 units now and manage a block in Kilimani. How do I transition to the Partner Track for higher agency payout percentages?',
        timestamp: '2026-09-03T07:10:00Z',
      },
    ],
  },
];
